version: "2.0"
meta:
  ERDA_COMPONENT: ""
values:
  production:
    docker_data_root: "<%$.Docker.DataRoot%>"
    platform_data_root: "<%$.Platform.DataRoot%>"
    replicas: 1
    request_cpu: 0.1
    request_mem: 128
  staging:
    platform_data_root: /data/staing
  development:
    platform_data_root: /data/staing
    docker_data_root: /data/docker/data
  test:
    platform_data_root: /data/test

envs: {}
services:
  fluent-bit:
    image: fluent-bit
    envs:
      LOG_LEVEL: error
      UPGRADE_1_4_0: 0
    resources:
      cpu: ${request_cpu:0.2}
      mem: ${request_mem:512}
      max_cpu: 1
      max_mem: 1024
      network:
        mode: container
    binds:
      - ${docker_data_root:/var/lib/docker}/containers:${docker_data_root:/var/lib/docker}/containers:ro
      - ${platform_data_root:/data}/spot-v2/fluent-bit:/data/spot/fluent-bit:rw
      - /var/log:/var/log:ro
    deployments:
      replicas: 1
      workload: per_node
      labels:
        GROUP: spot-v2
    health_check:
      http: {}
      exec:
        cmd: ps aux | grep fluent-bit || exit 1
        duration: 120
addons:
  infos:
    plan: "custom:basic"
    options:
      version: "1.0.0"
