version: "2.0"
meta:
  ERDA_COMPONENT: ""
values:
  production:
    docker_data_root: "<%$.Docker.DataRoot%>"
    platform_data_root: "<%$.Platform.DataRoot%>"
    replicas: 1
    request_cpu: 0.1
    request_mem: 128
envs: {}
services:
  fluent-bit:
    image: fluent-bit
    envs:
      COLLECTOR_AUTH_PASSWORD: G$9767bP32drYFPWrK4XMLRMTatiM6cU
      COLLECTOR_AUTH_USERNAME: collector
      OUTPUT_BATCH_TRIGGER_TIMEOUT: 10s
      OUTPUT_BATCH_TRIGGER_CONTENT_LIMIT_BYTES: 8388608
    resources:
      cpu: ${request_cpu:0.2}
      mem: ${request_mem:512}
      max_cpu: 1
      max_mem: 512
      network:
        mode: container
    binds:
      - ${docker_data_root:/var/lib/docker}/containers:${docker_data_root:/var/lib/docker}/containers:ro
      - /var/log:/var/log:ro
      - ${platform_data_root:/data}/spot-v2/filebeat:/data/spot/fluent-bit:rw
      #- ${platform_data_root:/data}/kube-apiserver/audit-logs:/data/kube-apiserver/audit-logs:ro
    deployments:
      replicas: 1
      workload: per_node
      labels:
        GROUP: spot-v2
    health_check:
      http: {}
      exec:
        cmd: ps aux | grep fluent-bit || exit 1
        duration: 120

addons:
  infos:
    plan: "custom:basic"
    options:
      version: "1.0.0"
